In [1]:
!pip install regex

In [2]:
import re

In [11]:
p = re.compile('\d+') # 0-9 digits
print(p.findall("I have 34 apples and 4 mangoes"))

['34', '4']


In [12]:
q = re.compile('\D+') # Non-digit
print(q.findall('I have 34 apples and 4 mangoes'))

['I have ', ' apples and ', ' mangoes']


In [13]:
e = re.compile('\s+') # White space character
print(e.findall('I have    3 apples and 4 mangoes'))

[' ', '    ', ' ', ' ', ' ', ' ']


In [7]:
f = re.compile('\S+') # Non-White space character
print(f.findall('I have 34 apples and 4 mangoes!@40'))

['I', 'have', '34', 'apples', 'and', '4', 'mangoes!@40']


In [8]:
g = re.compile('\w+') #Alphanumeric character 
print(g.findall('I have 3 apples and 4 mangoes!@40-'))

['I', 'have', '3', 'apples', 'and', '4', 'mangoes', '40']


In [9]:
h = re.compile('\W+') #Non-Alphanumeric Character
print(h.findall('I have 3 apples and 4 mangoes!@40'))

[' ', ' ', ' ', ' ', ' ', ' ', '!@']


In [28]:
height = [1.87,  1.87, 1.82, 1.91, 1.90, 1.85]
weight = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]
print(type(height))
# Import the numpy package as np
import numpy as np

# Create 2 numpy arrays from height and weight
np_height = np.array(height)
np_weight = np.array(weight)

<class 'list'>


In [26]:
print(type(np_height))

<class 'numpy.ndarray'>


In [27]:
# Calculate bmi
bmi = np_weight / np_height ** 2

# Print the result
print(bmi)

[23.34925219 27.88755755 28.75558507 25.48723993 23.87257618 25.84368152]


In [36]:
bmi > 25.488

array([False,  True,  True, False, False,  True])

In [32]:
bmi[bmi > 25.488]

array([27.88755755, 28.75558507, 25.84368152])

In [35]:
np_height > 1.83

array([ True,  True, False,  True,  True,  True])